//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.4
//
#import <AWSCore/AWSCore.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:4f8fca2c-6f6b-4c8f-b7fb-bf53fb5760c8"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub cc21d66c-097c-4691-9594-a6aacdd0cdd3 aws-my-sample-app-ios-objc-v0.4"
